### ISSUE TITLE
nonPublishable not working for Relationship field

### ISSUE THREAD

**Issue by PhilCuster** [Designory/keystone-publish#1]
KeystoneJS version: 4.0.0-beta.8

keystone-publish config:
```
var publishSettings = {
	keystone: keystone,
	stgPrefix: 'test',
};
publish.init(publishSettings);
```

Field in question:
```
framework: { type: Types.Relationship, ref: 'Framework', nonPublishable: true, required: true, initial: true },
```

The **Framework** model is nonPublishable yet I am getting errors when I launch:
```
ReferenceError: Unknown keystone list "testFramework"
```

I have tracked the faulty code to the following:
https://github.com/Designory/keystone-publish/blob/0a551a31984b90a4a9f3f4d45b63f561528e80fe/lib/PublishAddLists.js#L57-L61

When execution reaches the relevant **ref** `this.parent.keys.nonPublishable` still evaluates to false because `this.parent.keys` is an **Array** like the following:
```
0:"type"
1:"ref"
2:"nonPublishable"
3:"required"
4:"initial"
```

I would be happy to open a pull request with a fix. 😃

**Comment by PhilCuster** [comment]
Thanks!  Will there be a patch version bump?

**Comment by kmiddlesworth** [comment]
Hi @PhilCuster, I just published a version tick. Thanks again for the contribution!
